version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: gordon
      POSTGRES_DB: hello-actix
    ports: 
      - 5432:5432